### ISSUE TITLE
Annotate opcode type under encodings?

### ISSUE THREAD

**Issue by ksyx** [riscv/riscv-crypto#102]
As in B extension, adding this annotation like `OP_IMM` could save time locating them in the RISC-V spec table.

![image](https://user-images.githubusercontent.com/18738953/122349946-55ab0680-cf7f-11eb-8728-6dd5fe47a81a.png)

**Comment by ben-marshall** [comment]
I agree this is a nice to have. I don't know how Bitmanip generated these diagrams. I used the script in `bin/better-parse-opcodes.py`. So some modifications to that might do the trick. But, I certainly won't get to it for a while. This is very much a cosmetic change so not high priority (for me). Eventually I'm sure all RISC-V specs will have this, but it might not make the public review version of scalar crypto.

**Comment by kdockser** [comment]
This is a comment for the Scalar Crypto spec. Such changes are now the in domain of integrating specifications and making them consistent.
