### ISSUE TITLE
Does SMx algorithmes require clmuls?

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-crypto#129]
Zks enables Zbb, Zbc, Zbx. I am not sure that SMx do really require carry-less multiplication.
Probably, Zks should be _Zkb_Zkx_Zksed_Zksh?

**Comment by ben-marshall** [comment]
SM3/4 do not need CLMUL, likewise for AES. But CLMUL is very useful for the GCM mode of operation, which wraps SM4 or AES. Hence they often appear together in the extensions.
