### ISSUE TITLE
Encoding section minor beautification

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-crypto#133]
The encoding tables are beautiful in this extension!
But they may be even more beautiful (at least just a bit).

Some instructions may have OP[-IMM][-32] hint in the opcode field (chunk[6:0]):
aes32dsi
aes32dsmi
aes32esi
aes32esmi
aes64ds
aes64dsm
aes64es
aes64esm
aes64im
aes64ks1i
aes64ks2
packw
sha256sig0
sha256sig1
sha256sum0
sha256sum1
sha512sig0h
sha512sig0l
sha512sig1h
sha512sig1l
sha512sum0r
sha512sum1r
sha512sig0
sha512sig1
sha512sum0
sha512sum1
sm3p0
sm3p1
sm4ed
sm4ks
unzip
xperm8
xperm4
zip

Some instructions probably should not split chunk[31:30] and chunk[29:25]
because chunk[31:30] is not an immediate:
aes64ds
aes64dsm
aes64es
aes64esm
aes64im
aes64ks1i
aes64ks2
sha256sig0
sha256sig1
sha256sum0
sha256sum1
sha512sig0h
sha512sig0l
sha512sig1h
sha512sig1l
sha512sum0r
sha512sum1r
sha512sig0
sha512sig1
sha512sum0
sha512sum1
sm3p0
sm3p1

Some instructions probably should not split chunk[6:2] and chunk[1:0]
because... hrm, why should actually be splitted (?!):
packw
unzip
xperm8
xperm4
zip

Some instructions should probably split chunk[31:25] and chunk[24:20]
because chunk[24:20] is actually an immediate of more general instruction
brev8
rev8

Also I think that instruction-name hints should either be present in every insns or do not exist.

**Comment by ben-marshall** [comment]
I think the typography issues in the current spec will eventually be taken care of when the spec is merged into the main RISC-V specification, so thank you for providing a checklist of things when that is done!
