### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by mjosaarinen** [riscv/riscv-crypto#144]
Hi, 

In short, my impression is that GM/T 0005-2012 testing is often done on post-processed output, not the actual physical entropy. Is this correct?

So to me it seems that the at least the "old" GM/T 0005-2012 an RNG test, not an entropy source test. I looked at the requirements and it seemed very similar to the obsoleted 800-22 which was a test covering also pseudorandom output. Entropy sources do not need to pass 800-22 either.

Anyway, in terms of timelines, it would seem sensible to look closely at the newer standard and see if it is compatible with AIS-31 and SP 800-90B standards (the old one is not really compatible with AIS-31/PTG.2 or 90B, as it does not seem to concern entropy. just "statistical randomness"). If it is not compatible and there is still a need for ISA support, it will need a separate instruction or a CSR interface. The seed entropy source is specifically an entropy source.

Cheers,
- markku

_Originally posted by @mjosaarinen in https://github.com/riscv/riscv-crypto/pull/142#issuecomment-988712228_

**Comment by ben-marshall** [comment]
Is this where you meant to leave this comment? ;)

**Comment by mjosaarinen** [comment]
No!
