### ISSUE TITLE
Do we need an rv32/xperm8 insn?

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-crypto#146]
It seems like any rv32/xperm8 insn may be represented as rv32/xperm8 accurate to rs2 contents.
This is almost true in case of rv64 except that rv64/xperm4 can not zero-out a byte.

Is there any data about usability of xperm8 compared to xperm4 (i.e. less loads or some already stored constants for rs2)?
Is byte-zeroing really used in any algorithms?

I am not suggesting to change anything, just curious if there is something helpful already.

**Comment by kdockser** [comment]
Closing as this was a question related to Scalar Crypto no-one has responded in the last 10 months. There is nothing that needs to be done in any of the specifications relating to this issue.
