### ISSUE TITLE
SM3 example code

### ISSUE THREAD

**Issue by ben-marshall** [riscv/riscv-crypto#15]
- [ ] Implement a baseline RV32/RV64 version of SM3
- [ ] Implement an accelerated version of SM3 using the proposed instructions.

**Comment by mjosaarinen** [comment]
You're free to use the quantitive SM3 code I wrote in March. SM3 doesn't seem to benefit much (at all?) from RV64 -- there's only one hash size. The breakup of the functions matches that I used for SHA2 and SHA3 in the https://github.com/mjosaarinen/lwsha_isa/ repo.
* `sm3_rv32_cf.c`:  https://github.com/mjosaarinen/lwsha_isa/blob/master/sm3_rv32_cf.c  The compression function is the main optimization target. There the "instructions" are emulated by functions `sm3_p0()` and `sm3_p1` defined on the top of the file. Additionally, it uses bitmanip stuff, emulated by functions defined in `bitmanip.h` and `bitmanip.c`  
* `sm3_wrap.c`: https://github.com/mjosaarinen/lwsha_isa/blob/master/sm3_wrap.c with prototypes at `sm3_wrap.h` contains a single-call interface to the hash function that implements padding etc.  
* `sm3_test.c`: https://github.com/mjosaarinen/lwsha_isa/blob/master/sm3_test.c contains very limited testing for the function with two test vectors from the standard text itself.
