### ISSUE TITLE
How to generate Scalar Cryptography

### ISSUE THREAD

**Issue by ChunyuLiao** [riscv/riscv-crypto#155]
Is it usual to compile c programs directly to get instructions? Or is it enough to compile C builtin/intrinsic?

What other architectures implement similar Scalar Cryptography?

**Comment by kdockser** [comment]
In general, compilers are not equipped to compile high-level code to use highly specialized cryptographic instructions. The typical approach to creating cryptographic code is either through assembly language or through the use of intrinsics in a higher level language. Often, open source libraries are made available for implementing common cryptographic algorithms. [OpenSSL](https://github.com/openssl/openssl) is one such open source library that supports RISC-V scalar crypto instructions. By looking through the directories in the Open SLL repository you can find what other architectures have similar cryptographic instruction support.
