### ISSUE TITLE
Is Example seed CSR DEAD value correct?

### ISSUE THREAD

**Issue by dansmathers** [riscv/riscv-crypto#157]
In the Entropy Source section of the scalar spec it says: When OPST is not ES16, entropy must be set to 0.

but the Example below that statement has this example:
Example. 0x8000ABCD is a valid ES16 status output, with 0xABCD being the entropy value. 0xFFFFFFFF is an invalid output (DEAD) with no entropy value.

Shouldn't the DEAD example be: 0xC0000000 instead of 0xFFFFFFFF?  (entropy field must be set to 0)

**Comment by mjosaarinen** [comment]
0xFFFFFFFF is DEAD too. It may not be the most valid DEAD but it is what happens if there's no signal from the entropy source module.

**Comment by GDI123** [comment]
Can't agree with such answer.
We have requirement:` When OPST is not ES16, entropy must be set to 0. An implementation may safely set reserved and custom bits to zeros.`
No exclusion for DEAD state or any other conditions.
Thus we should have some Zkr logic which must set entropy to 0 if non-ES16 status received from entropy source.
Even if we got 0xFFFFFFFF from entropy source the same Zkr logic must set entropy to 0 and set reserved bits depending on the implementation.
Thus we should get 0xC0000000 or 0xFFFF0000 from SEED register depending on reserved bits handling implementation.
The same output we should get in any other DEAD codes passed from entropy source: 0xC000ABCD or 0xDABCDEFF without dependency on malfunction of entropy source or lost signal or something else.

**Comment by allenjbaum** [comment]
I agree with Dimity. The spec is very clear that the entropy field must be 0 if OPST is not ES16.
The example is not so clear;  it describes 0xFFFFFFFF  as an *invalid* output and thus should never be observed:   
    it is not spec compliant 
I agree that "Even if we got 0xFFFFFFFF from entropy source .... Zkr logic must set entropy to 0 ....
which can be done inside the entropy source, or outside, if you expect that lost communication with the entropy source is possible.

**Comment by allenjbaum** [comment]
> I agree with Dimitry. The spec is very clear that the entropy field must be 0 if OPST is not ES16. The example is not so clear; it describes 0xFFFFFFFF as an _invalid_ output and thus should never be observed: it is not spec compliant I agree that "Even if we got 0xFFFFFFFF from entropy source .... Zkr logic must set entropy to 0 .... which can be done inside the entropy source, or outside, if you expect that lost communication with the entropy source is possible.
