### ISSUE TITLE
can't git riscv-isa-sim

### ISSUE THREAD

**Issue by kczmudzin** [riscv/riscv-crypto#161]
Cloning into '/home/kczmudzi/riscv-crypto/extern/riscv-isa-sim'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:riscv/riscv-isa-sim' into submodule path '/home/kczmudzi/riscv-crypto/extern/riscv-isa-sim' failed
Failed to clone 'extern/riscv-isa-sim'. Retry scheduled
Cloning into '/home/kczmudzi/riscv-crypto/extern/riscv-isa-sim'...
ssh: connect to host github.com port 22: Connection timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:riscv/riscv-isa-sim' into submodule path '/home/kczmudzi/riscv-crypto/extern/riscv-isa-sim' failed
Failed to clone 'extern/riscv-isa-sim' a second time, aborting

**Comment by ibnelwalid** [comment]
I fixed this by using this url for riscv-isa-sim https://github.com/riscv-software-src/riscv-isa-sim
You can do this by git submodule set-url extern/riscv-isa-sim https://github.com/riscv-software-src/riscv-isa-sim
