### ISSUE TITLE
Suggest for rnd immediate value for vsm3c.vv in v0.1.2 vector crypto spec

### ISSUE THREAD

**Issue by timhsu404** [riscv/riscv-crypto#184]
The vsm3c.vv encryption should rotate the Tj constant by round count as following code shows.
```
SS1 <- ROTL7((ROTL12(A) + E + (ROTLjmod32(T_j))
```
The immediate value, `rnd`, needs to be in range from `0 to 63`.
Please help confirm the behavior, thanks.

**Comment by nibrunieAtSi5** [comment]
Hi,
   Thank you for reporting this issue. This has already been reported as a change request in the opcode spreadsheet last week: https://docs.google.com/spreadsheets/d/1yFnPYSJI7wCInsLTytPuSysZHQHhjUt5XtNLveFrGk8/edit?disco=AAAAewLNh40 and is under consideration by @kdockser . It should appear in a future update of the specification.

**Comment by timhsu404** [comment]
Hi,
Thanks for your mention.
I will close the issue and keep track on latest specification.
