### ISSUE TITLE
Incoherence of vl usage in operation section

### ISSUE THREAD

**Issue by timhsu404** [riscv/riscv-crypto#185]
According to latest master branch, the most element group calculation use only EGS and vl `eg = (vl/EGS)`.
But there is still some element group calculation include the SEW in it, as following code section shows.
Please help confirm the behavior.
```
//vaese128.adoc
eg = (vl/EGS)(SEW/EEW)
//vaeskr1, vaeskr2
vlen = vl/EGS * vtype.SEW/EEW
```

**Comment by timhsu404** [comment]
Tag them for tracking the issue.
@nibrunieAtSi5 @EricCheng2222

**Comment by kdockser** [comment]
This is just some stale text in the specification. I will remove it.

**Comment by kdockser** [comment]
Removed.

**Comment by nibrunieAtSi5** [comment]
Thanks @kdockser
