### ISSUE TITLE
Inconsistent use of foreach range bound

### ISSUE THREAD

**Issue by nibrunie** [riscv/riscv-crypto#187]
@kdockser It seems we are mixing two different usages of `<var> foreach <low> to <high> `: 
- one where `high` is excluded, for example when iterating over the element groups as in https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vaes128k10.adoc
```
  foreach (i from egstart to elementgroups) {
```

- one where `high` is included, for example when iterating over bits as in https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vclmul.adoc
```
  foreach (i from 0 to (EEW - 1)) {
```

Is my understanding incorrect ? If not, how should we unify the descriptions ?

**Comment by kdockser** [comment]
Hi Nicolas,

Right now the pseudo code is little more than a place holder. In some cases there is some initial thought put into the code, but not that much. We intend to replace all of the pseudo code with better and more consistent code. Initially this will be based on the code put into SPIKE. In the long term we would like to include SAIL code.

Thanks,
Ken
