### ISSUE TITLE
Include Scalar Cryptography in "Releases"

### ISSUE THREAD

**Issue by mjosaarinen** [riscv/riscv-crypto#188]
Hi,

I'd still include the alredy-ratified Part I (Scalar) in the releases, as it does not seem to be available elsewhere except in this repo.

The two recent ones only Part II (Vector), but that has not been ratified.

Cheers,
- markku

**Comment by kdockser** [comment]
Hi Markku,

All of the releases for Scalar Cryptography are available under [Releases ](https://github.com/riscv/riscv-crypto/releases). including the ratified[ Scalar Cryptography v1.0.1](https://github.com/riscv/riscv-crypto/releases/tag/v1.0.1-scalar). However, I think that GitHub only displays the most recent release in the Release box.

There has been talk about splitting out Vector and Scalar Crypto into separate repositories. I think that this makes sense but is also a lot of work. So, for now we sharing the repository.

Does this address your concern, or do you think that there is something else we should do now?

Thanks,
Ken
