### ISSUE TITLE
The vsha2c output need to be the same in latest crypto draft 20220916

### ISSUE THREAD

**Issue by timhsu404** [riscv/riscv-crypto#190]
The output format is dirrerent in description and pseudocode.
Which one should we follow?
```
vd = {a, b, e, f}; //in description
or
vd = {f,e,b,a); //in pseudocode
```

**Comment by timhsu404** [comment]
@nibrunieAtSi5 EricCheng2222 for issue tracing.

**Comment by nibrunieAtSi5** [comment]
@kdockser  it seems our ordering is not consistent in https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vsha2c.adoc

Should `a` be the least significant element (element 0, bytes 0 to 3 for SHA-256 and bytes 0 to 7 for SHA-512) or the other way around ?
How do we express this, I would have assumed: `{lowest element, ... , high element}` , is this correct ?

**Comment by kdockser** [comment]
We are in the process of cleaning up the pseudo code. This is one of the items will be resolved in these changes.

**Comment by kdockser** [comment]
This has been updated to be consistent between the pseudo-code and the specification.
