### ISSUE TITLE
Discussing vclmulgf alternatives

### ISSUE THREAD

**Issue by nibrunie** [riscv/riscv-crypto#192]
@kdockser and @mjosaarinen  to continue the discussion on `GHASH`:

![image](https://user-images.githubusercontent.com/15112260/193727820-7b120857-5ab4-4e1c-8a32-12cb645c3a62.png)

original diagram from wikipedia [Galois/Counter Mode](https://en.wikipedia.org/wiki/Galois/Counter_Model)

Assuming `Auth Data`, `Ciphertext <i>`, `H` as inputs and `Auth Tag` as output:
- the `MAC` is the best variant as it exactly tiles the algorithm.
- the `ACCMUL` variant requires an extra initial `mult_H` and an extra final `xor` (the former could be implemented as a `vghash` with a `0`-value ciphertext

# Proposed variant in a multi-stream decomposition #

## Multi-stream with MAC variant ##
```
H4V = {H^4, H^4, H^4, H^4}
HASH = {M_0, M_1, M_2, M_3}
for every 512 bits of message NM={M_4+i, M_4+i+1, M_4+i+2, M_4+i+3} // starting at i=1
   HASH = HASH  • H4V ⊕ NM
// eventually the signature must be reduce
RED = {H, 0, 0, 0}
// the following call to vclmulgf can be done on a single element group by limiting vl
HASH = HASH • RED ⊕ {M_4+i+1, M_4+i+2, M_4+i+3, 0} // addend is HASH slided down by 128 bits
HASH = HASH • RED ⊕ {M_4+i+2, M_4+i+3, 0, 0} 
HASH = HASH • RED ⊕ {M_4+i+3, 0, 0, 0}
HASH = HASH • RED ⊕ RED // final GHASH operation  
```

## Multi-stream with MULACC variant ##
```
H4V = {H^4, H^4, H^4, H^4}
HASH = {M_0, M_1, M_2, M_3}
HASH = (HASH ⊕ 0) • H4V  // initial operation with addend 0
for every 512 bits of message NM={M_4+i, M_4+i+1, M_4+i+2, M_4+i+3} // starting at i=1, excluding last chunk
   HASH = (HASH ⊕ NM) • H4V 
// last message chunk
NM={M_4+i, M_4+i+1, M_4+i+2, M_4+i+3}
HASH = (HASH ⊕ NM) • H4V 
// eventually the signature must be reduce
// this could be done with a 2 vredxor.vs e64, with proper masking (for odd/even 64-bit element) and than a vslideup
```

**Comment by nibrunieAtSi5** [comment]
The GHASH spec  https://nvlpubs.nist.gov/nistpubs/Legacy/SP/nistspecialpublication800-38d.pdf specifies (page 12) the main operation as 
```
For i = 1, ..., m, let Yi = (Yi-1 ⊕ Xi) • H
```
This correspond to the ACCMUL variant, but hide the extra initial `mult_H` and final `xor`.

**Comment by nibrunieAtSi5** [comment]
![image](https://user-images.githubusercontent.com/82109999/194380051-6cedc08b-fb05-44c8-96c9-18fa64762df6.png)

**Comment by nibrunie** [comment]
Proposed variant in a multi-stream decomposition

== Multi-stream with MAC variant
```
H4V = {H^4, H^4, H^4, H^4}
HASH = {M_0, M_1, M_2, M_3}
for every 512 bits of message NM={M_4+i, M_4+i+1, M_4+i+2, M_4+i+3} // starting at i=1
   HASH = HASH  • H4V ⊕ NM
// eventually the signature must be reduce
RED = {H, 0, 0, 0}
// the following call to vclmulgf can be done on a single element group by limiting vl
HASH = HASH • RED ⊕ {M_4+i+1, M_4+i+2, M_4+i+3, 0} // addend is HASH slided down by 128 bits
HASH = HASH • RED ⊕ {M_4+i+2, M_4+i+3, 0, 0} 
HASH = HASH • RED ⊕ {M_4+i+3, 0, 0, 0}
HASH = HASH • RED ⊕ RED // final GHASH operation  
```

== Multi-stream with MULACC variant
```
H4V = {H^4, H^4, H^4, H^4}
HASH = {M_0, M_1, M_2, M_3}
HASH = (HASH ⊕ 0) • H4V  // initial operation with addend 0
for every 512 bits of message NM={M_4+i, M_4+i+1, M_4+i+2, M_4+i+3} // starting at i=1, excluding last chunk
   HASH = (HASH ⊕ NM) • H4V 
// last message chunk
NM={M_4+i, M_4+i+1, M_4+i+2, M_4+i+3}
HASH = (HASH ⊕ NM) • H4V 
// eventually the signature must be reduce
// this could be done with a 2 vredxor.vs e64, with proper masking (for odd/even 64-bit element) and than a vslideup
```

**Comment by nibrunieAtSi5** [comment]
@mjosaarinen : the MAC version is better for implementation, as it allows the new message/ciphertext operand to be ready later than required in the ACCMUL variant.

**Comment by nibrunieAtSi5** [comment]
We can close this discussion since the `MAC` version was selected by the task group.
