### ISSUE TITLE
Opaque note in vbrev8.v description

### ISSUE THREAD

**Issue by topperc** [riscv/riscv-crypto#209]
The vbrev8.v description contains a note that says "In some ways this is similar to how the bit logical instructions operate." It wasn't clear to me what ways this note was referring to.

@aswaterman suggested it was saying that the behavior is similar to bitwise logical operations in that it doesn't depend on SEW.

I think this note could be improved or possibly removed depending on how important it is to make this comparison.

**Comment by kdockser** [comment]
I updated the text to completely convey the thought: In some ways this is similar to how the bit logical instructions operate in that SEW does not affect the function.
