### ISSUE TITLE
question on data independent mandate and vtype parameters

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#222]
The specification states:

> All cryptography-specific instructions defined in this Vector Crypto specification (i.e., Zvkns,
Zvknh[ab], Zvkg, Zvksed and Zvksh but not Zvkb) shall be executed with data independent
execution latency. That is, the latency of an instruction’s execution shall not vary based on the
values of its inputs. This behavior is the same as described as described in the Zkt extension for
scalar instructions. This behavior in these Vector Crypto instructions is independent of the
implementation of the Zkt extension; it does not require that Zkt is implemented.

Does this mandate include the `vl`, `sew`, `lmul` vtype values or simply the actual data (keys, cipher/plain texts, message ...) ?

**Comment by kdockser** [comment]
It applies just to the data itself. I have added clarifying text.
