### ISSUE TITLE
Does `vclmul` and `vclmulh` has a masked version?

### ISSUE THREAD

**Issue by eopXD** [riscv/riscv-crypto#227]
The description of `vclmul` [0] and `vclmulh` [1] mimics `vandn` [2].

From [0]:
> This instruction performs a carry-less multiply operation to all active elements in the vector register group specified by vs2. ...

The wording of "all active elements" makes me suspect that there is a masked version of the instruction that is missing for `vclmul` and `vclmulh`.

[0] https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vclmul.adoc
[1] https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vclmulh.adoc
[2] https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vandn.adoc

**Comment by nibrunie** [comment]
The masked version has been added to the encoding https://github.com/riscv/riscv-crypto/pull/223, it needs to be added to the description

**Comment by nibrunieAtSi5** [comment]
@eopXD , I have opened https://github.com/riscv/riscv-crypto/pull/229 to add mask operand in the mnemonic description

**Comment by kdockser** [comment]
The spec has been updated by accepting the pull request.
