### ISSUE TITLE
Vector SHA2 Mock SAIL code.

### ISSUE THREAD

**Issue by ben-marshall** [riscv/riscv-crypto#23]
Write pseudo-code descriptions of the vector SHA2 instructions. Because there is no support for the base vector extension, these functions assume that extraction of input elements from the vector registers is a solved problem and that they are just passed in as arguments. The mocked functions just return the result for a single set of elements. They *do not* change any architectural state.
- [X] SHA256 Utility functions: sig/sum/ch/maj
- [X] SHA512 Utility functions: sig/sum/ch/maj
- [x] Single Round Message SHA256
- [x] Single Round Working State SHA256
- [x] Single Round Message SHA512
- [x] Single Round Working State SHA512
- [ ] All Round SHA256.
- [ ] All Round SHA512.

**Comment by kdockser** [comment]
The SHA-2 instructions have been address using SAIL-like code. That will need to do for now until there is SAIL support for RISC-V vectors.
