### ISSUE TITLE
Legal range of uimm in instruction `vaeskf2.vi vd, vs2, uimm`

### ISSUE THREAD

**Issue by DavidYuSi5** [riscv/riscv-crypto#232]
In the spec, the legal range of uimm in `vaeskf2 vd, vs2, uimm` is
```
Legal values are 1 - 14.
```
but we already have the round-1 key, the second half of the 256-bit key.
Should the valid range be `2 - 14`?

**Comment by nibrunieAtSi5** [comment]
I opened https://github.com/riscv/riscv-crypto/pull/238 to fix what I think is an error in the spec.

**Comment by kdockser** [comment]
Accepted Nicolas' pull request that made this fix.
