### ISSUE TITLE
Vector AES Mock SAIL code.

### ISSUE THREAD

**Issue by ben-marshall** [riscv/riscv-crypto#24]
Write mocked SAIL descriptions of the vector AES instructions. Because there is no support for the base vector extension, these functions assume that extraction of input elements from the vector registers is a solved problem and that they are just passed in as arguments. The mocked functions just return the result for a single set of elements. They *do not* change any architectural state.

**AES 128 Single Round:**
- [x] AES 128 KSE Single Round
- [ ] AES 128 KSD Single Round
- [x] AES 128 ENC Single Round
- [ ] AES 128 DEC Single Round

**AES 128 All Round:**
- [x] AES 128 KS All Rounds
- [x] AES 128 ENC All Rounds
- [ ] AES 128 DEC All Rounds

**AES 256 Single Round:**
- [x] AES 256 KSE Single Round
- [ ] AES 256 KSD Single Round
- [x] AES 256 ENC Single Round
- [ ] AES 256 DEC Single Round

**AES 256 All Round:**
- [x] AES 256 KSE All Rounds
- [x] AES 256 ENC All Rounds
- [ ] AES 256 DEC All Rounds

**Comment by kdockser** [comment]
Until the Sail model for RISC-V Vector is complete, we cannot add in modifications to SAIL needed for Vector Crypto. Instead, the specification will continue to use SAIL-like code in the fashion that Ben had created.
