### ISSUE TITLE
Is `vsm4r.vs` still a valid instruction in vector crypto spec?

### ISSUE THREAD

**Issue by DavidYuSi5** [riscv/riscv-crypto#243]
If so, the description of `vsm4r.vs` is missing in Section 3.21. If not, should remove `vsm4r.[vv,vs]` in Section 2.5.

(based on document 20221125)

**Comment by nibrunieAtSi5** [comment]
That is a good question.

**Comment by nibrunieAtSi5** [comment]
Open https://github.com/riscv/riscv-crypto/pull/248 to add it back

**Comment by kdockser** [comment]
Thanks for catching this omission, David. We had assigned an encoding for this but mistakenly left it out of the specification. It has now included in the specification.
