### ISSUE TITLE
Is there a need for a non bit reversed `vghmac.vv` ?

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#244]
It seems like the AES-XTS standard is using a galois field multiplication with the same irreducible polynomial as GCM but without bit reversing every byte.

![image](https://user-images.githubusercontent.com/82109999/204897397-571f068d-f98f-4394-b0ef-14e3d2bfb92b.png)

if my understanding is correct, it could benefit from a modified version of `vghmac.vv` without bit reversal as this will save two `vbrev8` instructions.

### Reference
- https://luca-giuzzi.unibs.it/corsi/Support/papers-cryptography/1619-2007-NIST-Submission.pdf

**Comment by nibrunieAtSi5** [comment]
Task group discussion: the AES-XTS should not need a full GF multiplication: it is just a multiplication (shift) and reduction when required.

**Comment by kdockser** [comment]
Thanks for bringing this up Nicolas. As you noted in your reply, the TG decided that this was not needed.
