### ISSUE TITLE
Confirmation on imm for vandn.vi

### ISSUE THREAD

**Issue by eopXD** [riscv/riscv-crypto#245]
Just to confirm, is the `imm` input intended to be a signed-extended immediate? I am under the impression now that most vector crypto instructions are operating on unsigned elements. Also, this instruction is under the bit-manipulation extension `Zvkb`, so I suspect that we will always deal with unsigned elements here.

Please correct me if I am wrong.

**Comment by kdockser** [comment]
Thanks for the question. While this may differ from other vector crypto immediate instructions, what the specification says is intended: for vandn.vi the immediate is signed. This is consistent with other logical vector-immediate instructions in the Vector specification.
