### ISSUE TITLE
Question on vsm3c.vi

### ISSUE THREAD

**Issue by eopXD** [riscv/riscv-crypto#247]
Other instructions that takes a `uimm` has its mnemonics like:

```
vaeskf1.vi vd, vs2, uimm
```

Is there a reason why `vsm3c.vi` does not follow such consistency and use the wording `rnds` in the mnemonics?

```
vsm3c.vi vd, vs2, rnds
```

**Comment by kdockser** [comment]
Not a good a reason. I have fixed this.
