### ISSUE TITLE
Vector crypto require `zve32x` or `v`?

### ISSUE THREAD

**Issue by kito-cheng** [riscv/riscv-crypto#253]
Spec didn't mention which vector extensions is required as minimal requirement? does it require `zve32x` or it require `v`?

NOTE: `V` and `Zve*` has specify extension requirement in https://github.com/riscv/riscv-v-spec/blob/master/v-spec.adoc#18-standard-vector-extensions

**Comment by kdockser** [comment]
Thanks for bringing this up. The spec has been updated to indicate that any vector base can be used with most of the vector extensions. The only limitation is on Zvknhb (i.e., SHA-512) which requires ELEN>32.

- clmul[h].vx allows for a full 64x64 multiply when XLEN=64
