### ISSUE TITLE
What are the justification for `vsha2` state ordering in vector registers ?

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#258]
cc @DavidYuSi5

The word ordering used for the `vsha2c` instruction, namely `{a, b, c, d, e, f, g, h}` (where `a` is the most significant element and `h` the least significant element) seems a bit counter intuitive. I don't recall the reason for this ordering, is it to match the Secure Hash spec ?

![image](https://user-images.githubusercontent.com/82109999/208863092-4ac49e69-c083-4ea5-8938-7e29ad067ad1.png)

It seems RIVOS test code implements a word swap (on top of the word permute required)
(pointed out by David)
https://github.com/rivosinc/riscv-code-samples/blob/main/zvk-vector-crypto/sha-test.c#L77
```
	hash[0] = a;
	hash[1] = b;
	hash[2] = c;
	hash[3] = d;

	hash[4] = e;
	hash[5] = f;
	hash[6] = g;
	hash[7] = h;
```

**Comment by kdockser** [comment]
We decided to use this ordering to match the NIST spec [FIPS 180-4 (DOI)](https://doi.org/10.6028/NIST.FIPS.180-4).
We also chose it to match the order used by similar instructions in leading architectures.

I have accepted your pull request which addresses a typo in the spec pseudo code for vsha2c, but doesn't change the intended ordering of elements.

**Comment by nibrunieAtSi5** [comment]
Thank you @kdockser
