### ISSUE TITLE
clarifying vaes vd/vs2 overlap constraint

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#260]
Currently, for `vaes*` instructions the spec seems to indicate that overlap between `vs2` and `vd` is only forbidden for the `.vs` variant (this would make sense as overlap create RaW hazard with `vs2` which could be used with several registers in `vd` group). This fact is not very clear in the spec, could it be worth it to clarify that this constraint really only apply to the `.vs` variant.

https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vaesem.adoc

**Comment by kdockser** [comment]
Clarified in latest draft.
