### ISSUE TITLE
Draft spec version number and date unmodified

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#263]
The latest draft of the spec is still labelled v.0.0.1 and list the date Dec 8th (when it was generated Dec 20th), this is confusing and does not help to differentiate the version states of the draft spec.

![image](https://user-images.githubusercontent.com/82109999/210582028-e475dd71-1f03-4586-a27b-01e39b45cde4.png)

**Comment by kdockser** [comment]
Thanks for pointing this out, I have not given much attention to updating the revision number and date. Since we are rapidly approaching freeze and will be making such updates to avoid confusion.
