### ISSUE TITLE
clarify word order in pseudocode

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-crypto#266]
I'm getting confused about what word order is expected for VAES instructions in the pseudocode. For example, `vaeskf1.vi` has this bit of pseudocode:

`
let CurrentRoundKey[3:0]  : bits(32)  = get_velem(vs2, EGW=128, i);
`

Given this declaration, with `SEW=32` (as required for this instruction), does `CurrentRoundKey[0]` map to the element with _lowest_ index or _highest_ index?

Thanks.

**Comment by kdockser** [comment]
The indicies of the words match the indicies of the elements. Therefore, CurrentRoundKey[0] maps to the element with lowest index.
