### ISSUE TITLE
Comparing vaes instructions with Intel equivalents

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-crypto#275]
This isn't a functional issue that requires correction, but an observation about correspondence between `vaes` instructions and their IA64 equivalents, focusing on performance.

Three of the `vaes` instructions have exact correspondence with IA64 equivalents:

`vaesem.v[vs]` corresponds to IA64 `vaesenc`
`vaesef.v[vs]` corresponds to IA64 `vaesenclast`
`vaesdf.v[vs]` corresponds to IA64 `vaesdeclast`

However, `vaesdm.v[vs]` does not correspond to IA64 `vaesdec`. This is not a bug, but a result of the IA64 instruction being implemented like this:

```
STATE ← InvShiftRows( STATE );
STATE ← InvSubBytes( STATE );
STATE ← InvMixColumns( STATE );
DEST[127:0] ← STATE XOR RoundKey
```

Compared to the AES specification, the last two lines are reversed. This would obviously be incorrect if used in isolation, but in the IA64 instruction set there is an additional instruction, `vaesimc`, which implements the `InvMixColumns` transformation on the source. The intended use model is that there is a first pass to transform the round keys using `vaesimc` followed by a second pass using the `vaesdec` instruction to perform the decryption.

It seems from my superficial scan of the literature that, although the decryption code using these instructions is less obvious, these instructions were chosen because better performance was possible because of pipeline issues. I'm absolutely not a processor design expert so can't comment on whether this is correct or not, but I thought I would raise this in case it is significant.

Please feel free to close this issue immediately if this is of no significance to the RISC-V implementation.

Thanks.

**Comment by kdockser** [comment]
Thanks for bringing this up, James.

Intel has adopted a slight variation on what [NIST FIPS-197](https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=901427) refers to as the Equivalent Inverse Cipher. As you point out, this version requires different round keys to be used for decryption.

The intended advantage of Equivalent Inverse Cipher is it allows the steps for encryption and decryption to be in the same order:

- (Inv) SubBytes
- (Inv) ShiftRows
- (Inv) MixColumns
-  AddRoundKey

In theory this would allow the same _hardware_ pipeline to be used for encryption and decryption. However, the inverse operations are different enough from the forward operations that they typically use different logic. Furthermore, the only practical difference between the two inverse ciphers is (as you pointed out) the order of Inv-MixColumns and AddRoundKey. However, AddRoundKey is just an XOR and there is little savings (relatively speaking) in reusing those gates for last stage of both forward and inverse.

Our choice for how `vaesdm.v[vs]` is implemented was primarily motivated by softwares ability to use the same round key for both directions of the cipher.

**Comment by camel-cdr** [comment]
There is another advantage to the RISC-V implementation: you don't need a separate (Inv)MixColumns instruction.

x86 has a 128-bit only aesimc to invert the key.
If you want to compute InvMixColumns in RVV, you can simply execute `vaesdm.vv` with `vd=ShiftRows(SubBytes(0))=0x63636363…`, which forces the LHS of the XOR to zero, so vs2 is directly passed through to InvMixColumns.
