### ISSUE TITLE
meta extension defined in RVA23 profiles

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#285]
It looks like RVA23 introduces optional support for NIST and ShangMi algorithms support through `Zvks` and `Zvkn`. 
https://github.com/riscv/riscv-profiles/blob/main/rva23-profile.adoc#rva23u64-optional-extensions

I think these covers `Zvksed` and `Zvksh` (respectively `Zvknh[ab]` and `Zvkns`), should we define those meta-extensions in the spec ?

**Comment by kdockser** [comment]
Thanks for brining this up. We definitely do not to defined these.
I have updated the spec with the definitions of Zvks and Zvkn that we agreed to in yesterday's TG.
