### ISSUE TITLE
Compliance Tests: Vector Instructions

### ISSUE THREAD

**Issue by ben-marshall** [riscv/riscv-crypto#29]
Create [riscv-compliance](https://github.com/riscv/riscv-compliance/) tests for the cryptography extension *or* explain why we can't in some cases.
- A [useful document](https://docs.google.com/document/d/1U6qTBGhaR5hipxxC5z7-L2GQazAXhe79sgc3KscNme8/edit) on *what* the architectural compliance tests are and what they try to achieve.
- [Compliance Test Suite Documentation](https://github.com/riscv/riscv-compliance/blob/master/doc/README.adoc)

**Vector Instructions: AES**
- [ ] Vector AES Per Enc Round (vector-scalar)
- [ ] Vector AES Per Enc Round (vector-vector)
- [ ] Vector AES Per Dec Round (vector-scalar)
- [ ] Vector AES Per Dec Round (vector-vector)
- [ ] Vector AES Per Round 128 KeyI
- [ ] Vector AES Per Round 192 KeyI
- [ ] Vector AES Per Round 256 KeyI
- [ ] Vector AES Per Round 128 InvKeyI
- [ ] Vector AES Per Round 192 InvKeyI
- [ ] Vector AES Per Round 256 InvKeyI
- [ ] Vector AES All Round Enc 128 (vector-scalar)
- [ ] Vector AES All Round Enc 192 (vector-scalar)
- [ ] Vector AES All Round Enc 192 (vector-scalar)
- [ ] Vector AES All Round Enc 128 (vector-vector)
- [ ] Vector AES All Round Enc 192 (vector-vector)
- [ ] Vector AES All Round Enc 192 (vector-vector)
- [ ] Vector AES All Round Dec 128 (vector-scalar)
- [ ] Vector AES All Round Dec 192 (vector-scalar)
- [ ] Vector AES All Round Dec 192 (vector-scalar)
- [ ] Vector AES All Round Dec 128 (vector-vector)
- [ ] Vector AES All Round Dec 192 (vector-vector)
- [ ] Vector AES All Round Dec 192 (vector-vector)
- [ ] Vector AES All Round Revers Key 128
- [ ] Vector AES All Round Revers Key 192
- [ ] Vector AES All Round Revers Key 256

**Vector Carry-less Multiply:**
- [ ] `vclmul.vv`
- [ ] `vclmul.vs`
- [ ] `vclmulh.vv`
- [ ] `vclmulh.vs`
- [ ] `vclmacc.vv`
- [ ] `vclmacc.vs`
- [ ] `vclmacch.vv`
- [ ] `vclmacch.vs`
- [ ] `vwclmul.vv`
- [ ] `vwclmul.vs`
- [ ] `vwclmacc.vv`
- [ ] `vwclmacc.vs`

**Vector SHA2:**
- [ ] `vsha2.ms` (SHA256)
- [ ] `vsha2.ms` (SHA512)
- [ ] `vsha2.ws` (SHA256)
- [ ] `vsha2.ws` (SHA512)
- [ ] `vsha2.hs` (SHA256)
- [ ] `vsha2.hs` (SHA512)

**Vector Rotate:**

- [ ] `vrot.vv`

**Vector Grev:**

- [ ] `vgrev.vi`

**Comment by kdockser** [comment]
RISC-V Vector Cryptography Extensions Compatibility tests need to leverage the Vector Compatibility Tests which have yet to be  approved. This task is tracked as part of the Extension Deliverables and therefore does not need to be tracked here as well.
