### ISSUE TITLE
About vector EEW elements reversion instruction.

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-crypto#298]
In `sha256/512`, `gcm` and `sm4`, we might use vss(Vector Strided Store) with negative stride to store the elements in reversed order.
I think the `vss` it not efficient in hw implementation. Could we have additional instruction to do the EEW based reversion instruction?
Thus, we could do the reversion and use regular vs(Unit-Stride Store) for better memory pattern.

**Comment by nibrunieAtSi5** [comment]
What would be the difference with `vrev8.v` instruction, you want a word reversal within VLEN ?

**Comment by JerryShih** [comment]
No, I mean reorder the EEW elements in EGW.

e.g.
The last step of SM4.
```
(Y_0, Y_1, Y_2, Y_3) = R(X_32, X_33, X_34, X_35) = (X_35, X_34, X_33, X_32)
```

**Comment by nibrunieAtSi5** [comment]
> No, I mean reorder the EEW elements in EGW.
> 
> e.g. The last step of SM4.
> 
> ```
> (Y_0, Y_1, Y_2, Y_3) = R(X_32, X_33, X_34, X_35) = (X_35, X_34, X_33, X_32)
> ```

Yes, sorry this this what I meant by `word reversal`. I should have said "elements reversal in element groups".

**Comment by kdockser** [comment]
The elements within an element group can be reordered using the existing `vrgather` instruction.
