### ISSUE TITLE
Could we have additional `vghsh` variant `vghsh.vs`?

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-crypto#299]
We probably have the following code for GCM mode.
The loop will iterate all EGW blocks(EGW=128bits) one bye one.

```
vghsh.vv vd, vs2, vs1
```

```
# void gcm_ghash_rv64i_zvkg(u64 Xi[2], const u128 Htable[16],
#                           const u8 *inp, size_t len);

    vsetivli zero, 4, e32, m1, ta, ma
    vle32.v vH, (a1)
    vle32.v vXi, (a0)

Lstep:
    vle32.v vInput, (a2)
    addi a2, a2, 16
    addi a3, a3, -16
    vghsh.vv vXi, vH, vInput
    bnez a3, Lstep

    vse32.v vXi, (a0)
    ret
```

If we have `vghsh.vs` variant which take a single EGW `vH` over all data in the `vs1`, we could reduce dynamic code size using larger vl size.

The pseudo code for `vghsh.vs` looks like:
```
   function clause execute (VGHSH(vs2, vs1, vd, suffix)) = {
    // operands are input with bits reversed in each byte
    if( ((vl%EGS)<>0) | ((vstart%EGS)<>0) | (LMUL*VLEN < EGW))  then {
      handle_illegal();  // illegal instruction exception
      RETIRE_SUCCESS
    } else {
      eg_len = (vl/EGS)
      eg_start = (vstart/EGS)
      foreach (i from eg_start to eg_len-1) {
        let H_elem = if suffix == "vv" then i else 0;
        let Y = (get_velem(vd,EGW=128,i));  // current partial-hash
        let X = get_velem(vs1,EGW=128,i);  // block cipher output
        let H = brev8(get_velem(vs2,EGW=128, H_elem)); // Hash subkey
        .....
    }
```

**Comment by nibrunieAtSi5** [comment]
I think we did not include `vghmac.vs`/ `vghsh.vs` because contrary to the ciphers the `H` value does not change accross rounds so it should be pretty easy to splat it over a vector register group and use it in with a `vghsh.vv`, with the caveat of increased register pressure compare to what you are suggesting. 
Let's discuss that with a larger audience (@kdockser ?) to see if it could make sense to add it (opcode availability, ...).

**Comment by JerryShih** [comment]
We need to prepare that vector using several vslide/vmerge instructions. If we still have encoding space, it's much convenient to use ".vs" form.

**Comment by nibrunieAtSi5** [comment]
You can use `vaesz.vs` and `vxor.vv` to splat easily the H value.

**Comment by nibrunieAtSi5** [comment]
See end of https://fprox.substack.com/p/risc-v-vector-cryptography-extensions

**Comment by kdockser** [comment]
I agree with Nicolas, the vector holding the H values is generated once and then used over multiple iterations. This is very different from something like AES where you are constantly changing the round key.
We decided against defining a .vs version of the GHash instructions because the savings they would provide would be minimal at best.

**Comment by nibrunieAtSi5** [comment]
Adding a few elements here from a discussion with @grnewell 

- `GHASH` is not as trivial to vectorize as a parallel block cipher (cf https://github.com/riscv/riscv-crypto/issues/192 & https://github.com/riscv/riscv-crypto/issues/284 ) so parallel implementation will require more care and code is expected to be complex (with or without `.vs`)
- as mentioned by @kdockser , the `H` is pseudo-constant and does not occupy as much space as multiple rounds of a key so the register impact of having to splat it once should be limited (in particular for implementation with larger LMUL where splat once reuse multiple times does not necessarily incur reusing larger register groups)


NOTE `H` appears on the `vs2` operand so could be compatible with the `.vs` variant, which splats this `vs2` operand for other operation.

**Comment by JerryShih** [comment]
I'm trying to implement the aes-gcm with parallel blocks. I suggest to have the `.vs` form to reduce the register pressure. If we only have `.vv` form, we need to have the 3X registers number. If we use LMUL=4, we need to use 12 register with `.vv` form, but we only need 9 registers with `.vs` form.
The AES extensions have `.vs` form for all instructions.
```
vghsh.vv vd, vs2, vs1
```

cc @nibrunieAtSi5 @kdockser

**Comment by kdockser** [comment]
Thanks for your comments, Jerry.
One way to reduce the number of registers required in your example is to use LMUL=1 with four instances of the `vghsh.vv` instruction. That way, all 4 can use the same register to hold **_H_** . Granted the code will not be quite as compact as with LMUL=4, but it will still be small.

You would typically execute one instance of this code after you have gone through all of the AES encryption rounds for each block, or before you go through all of the AES decryption rounds.

**Comment by nibrunieAtSi5** [comment]
I think the large use of registers appears when there is a rather small VLEN and a large LMUL used at the same time. In that particular case `.vs` could be rather benefitial (in particular for implementation with few physical registers). For implementation with more physical registers (e.g. with architectural -> physical renaming) it should make less of a difference (although I have not evaluated it).

**Comment by JerryShih** [comment]
> Thanks for your comments, Jerry. One way to reduce the number of registers required in your example is to use LMUL=1 with four instances of the `vghsh.vv` instruction. That way, all 4 can use the same register to hold **_H_** . Granted the code will not be quite as compact as with LMUL=4, but it will still be small.

The algorithm I try to use is here: https://github.com/riscv/riscv-crypto/issues/192#issuecomment-1270447575
The 4 blocks of ciphertext will be multiply by H^4 and then go to the next 4 blocks.
With `vghsh.vv`, I will need the LMUL=4 register for the `H^4` vector(assume VLEN=128).
If we use LMUL=1 to process the H factor, we need to use `vslide*` instruction to permutate the ciphertext in the LMUL=4 register.

With `.vs`, we could have more register space to handle more blocks of ciphertext or do software-pipelining.

@kdockser

**Comment by kdockser** [comment]
I'm not following your comment about needing LMUL=4 to generate H^4.

H^4 can be generated with LMUL=1 (and vl=4) by using the `vgmul.vv` instruction twice; once to create H^2 and a second time to create H^4. No additional registers or `vslide*` instructions are needed as H and it's products over GF(2^128) are always 128-bits.

If you write out your example case in assembly code, I'd be happy to go over it with you.

The Vector Crypto specification has been submitted to the Architectural Review Committee for final review after several months of back-and-forth discussions. We are, for all intents and purposes, frozen. We could only a consider a change like this if there were no viable alternatives. However, in this case you could achieve the same end by using LMUL:=1 rather than LMUL=4.

**Comment by nibrunieAtSi5** [comment]
I think LMUL=4 matches the 4-wide vector of 128-bit block described in Richard's slides to present the parallel GHASH algorithm. This is just illustrative as the algorithm can be expanded with other vector width, e.g. 2-wide . The efficiency will depend on the actual machine width and the pipeline depth.

**Comment by kdockser** [comment]
Jerry, thanks for sharing your code.

I agree that you would need 3 extra registers to hold H^4 if you used VMUL=4 for the `vghsh.vv` instruction. However, you only need 29 vector registers for your loop with the instruction as is. 

```
 4 registers for plain text
 4 registers for cipher text
13 registers for AES-256 round keys
 4 registers for partial hash
 4 registers for H^4
Total: 29 registers
```

There are a variety of ways to splat H^4 across all of the element groups; the overhead of this shouldn't matter as it is amortized over all of the block of of the message.

If you _needed_ to reduce the number of registers used by 3, you could change from LMUL = 4 to LMUL = 1 for the GHASHing,  and perform this with 4 `vghsh.vv` instructions, each operating on 128 bits

```
vsetivli zero, 4, e32, m1, ta, ma
vghsh.vv vPartialTag,   vH4, vCipherText
vghsh.vv vPartialTag+1, vH4, vCipherText+1
vghsh.vv vPartialTag+2, vH4, vCipherText+2
vghsh.vv vPartialTag+3, vH4, vCipherText+3
```

I agree that a `.vs` form of `vghsh` could be _useful_. However, it is not _necessary_ to archive peak performance. Therefore, the need is not sufficient for us to open up the spec yet again and make changes to Spike, QEMU, glibc,etc..

**Comment by kdockser** [comment]
Reopening due to on-going discussion

**Comment by kdockser** [comment]
Thanks for your reply, Jerry.

I agree that we need to account for holding, incrementing and copying the counters into `cyphertext. It would be good if you added that to your example code so others could see everything in context. If we add 4 registers for the counters and go with the approach that I suggested, the loop would only consume 30 registers. Furthermore, there are techniques for reducing the register pressure including loading some (or all) of the round keys from memory.

I don't follow how the .vs form would allow us to use LMUL=8 as all 32 of the registers would be consumed with the `plain text`, `cipher text`, `counters`, and `partial hash`. You still need (up to 13) registers for the round keys and at least 1 register for `H^4` Furthermore, while I see value in LMUL=4 in that it can hide the latency of the AES instructions, I don't see much additional advantage to using LMUL=8 over using twice as many iterations through the loop.

The method that I mentioned for going from LMUL=4 to LMUL=1 with four copies of the `vghsh.vv` instruction works for any VLEN>=128. Just to be clear, `vPartialTag` and `vCipherText` refer to register numbers, not element groups. In fact, the 128-bit element groups only need to be combined once at the end of the message; this needs to be done no mater what the VLEN  is.

Thanks,
Ken

**Comment by kdockser** [comment]
After much deliberation on this matter, we have concluded that it is better to bring the current vector crypto specification to freeze rather than to delay it until the software collateral needed for freeze could be produced for this variant. The lack of resources available to create this collateral made this delay effectively unbounded.
