### ISSUE TITLE
5-bit shift for vwsll.vi

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#318]
for the `.vi` variant of `vwsll.vi`, the shift amount is limited to the lowest `log2(2*SEW)` bits.

```
      get_velem(vs2, i) << (imm[4:0] & ((2*SEW)-1))
```

Assuming an implementation with `ELEN=64`, `vwsll.vi` for `SEW=32` is supported and the shift amount is 6-bit wide (which is not possible for the immediate), I assume `imm[4:0]` is zero-extended before being AND-ed with the mask `(2*SEW)-1)`. Is that correct ? (should it be written down explicitly in the spec as suggested in https://github.com/riscv/riscv-crypto/pull/317)

Related issue: https://github.com/riscv/riscv-crypto/issues/312

**Comment by kdockser** [comment]
Thanks for catching this and making the clarification.
