### ISSUE TITLE
vwsll description could be more explicit that the input is first zero extended before performing the shift.

### ISSUE THREAD

**Issue by topperc** [riscv/riscv-crypto#328]
As opposed to sign extended or filled with random values.

cc: @nibrunie

**Comment by nibrunieAtSi5** [comment]
I agree that the description should mention explicitly that the input data element is zero-extended from `SEW` to `2 * SEW` before being shifted left logically.

**Comment by nibrunieAtSi5** [comment]
Addressed by @aswaterman in https://github.com/riscv/riscv-crypto/pull/329

**Comment by kasanovic** [comment]
Fix merged.
