### ISSUE TITLE
Zvkb is still mentioned in riscv-crypto-vector-inst-table.adoc

### ISSUE THREAD

**Issue by topperc** [riscv/riscv-crypto#334]
This text appears there

```
OP-P (0x77)
--
6 | Crypto Vector instructions except Zvkb
```

**Comment by nibrunieAtSi5** [comment]
Thank you for reporting it @topperc, I filed https://github.com/riscv/riscv-crypto/pull/335 to fix this.

**Comment by kdockser** [comment]
Thanks for finding this Craig.
Thanks for fixing it Nicolas.
