### ISSUE TITLE
Should Zvkt DIEL mandate cover immediate and register index values ?

### ISSUE THREAD

**Issue by nibrunieAtSi5** [riscv/riscv-crypto#343]
follow-up of a discussion held during July 13th Task group meeting (with @kdockser , @mjosaarinen  and others)

**Question**: Should Zvkt DIEL mandate also cover immediate values and static value registers ?

Rephrasing:
- Q1. Should  `vop.vi vd, vs2, imm` be forced to expose a latency which is independent from `imm` value ?
- Q2. Should `vop.vx vd, vs2, x0` latency be indistinguishable from `vop.vx vd, vs2, x<i>` (i != 0) when GPR[x<i>] === 0 ?

Some reference from Zkt (https://github.com/rvkrypto/riscv-zkt-list/blob/main/zkt-list.adoc#some-notes-on-rationale)
> Binary executables should not contain secrets in the instruction encodings (Kerckhoffs’s principle), so instruction timing may leak information about immediates, ordering of input registers, etc. There may be an exception to this in systems where a binary loader modifies the executable for purposes of relocation — and it is desirable to keep the execution location (PC) secret. This is why instructions such as LUI, AUIPC, and ADDI are on the list.

Q2 does not apply to `x0` only, but this is where it may be the most interesting (as `x0` is hard-wired to 0)

The register index value  cannot arguably be considered as part of the data so I would argue that `Q2` as a pretty straightforward answer: the execution latency of an instruction under a DIEL mandate can still depend on the value of the indices of the registers used as source / destination.

Let us now consider the dependency on the immediate value:

Pros (for considering the value of the immediate as a data covered by the DIEL mandate):
- Not introducing a distinction between the various operand types of an instruction

Cons:
- The immediate value is part of the opcode (so different immediate values imply [as for the register indices] different instructions)
- Removing this mandate does not affect security (an immediate value or a register index are never part of a secret and should never be)
- Allowing more implementation freedom by not mandating extra constraints and allowing micro-architectures to optimize some specific cases as the implementer see fit without compromising the conformity to Zvkt

For the last point, I do not have strong examples. `vwsll.vi vd, vs2, 0` or `vwsll.vx vd, vs2, x0` could be an interesting thing to optimize for a micro-architecture, but it can be replaced by a vzext.vf2 although this require a different `vlmul`/`vsew` setting (as SEW is used for `vwsll` source and `vzext.vf2` destination and similarly for LMUL: `vwsll` destination EMUL is `2*LMUL` while it is `LMUL` for `vzext.vf2`).

Similarly `vmv.v.i` could also be optimized on a data dependent fashion (I assumed some immediates are more used than others but I did not check any codebase).

**Comment by kdockser** [comment]
The spec had been updated to explicitly state that DIEL does not apply to constants specified in the instruction encoding such as immediate values and the zero register _x0_.
