### ISSUE TITLE
Are any of Zvkn/Zvks/Zvkg included in Zvkt?

### ISSUE THREAD

**Issue by aamartin0000** [riscv/riscv-crypto#357]
By omission in the Zvkt spec, can I assume that all of the above subsets are exempt from DIEL?
The scalar crypto Zkn and Zks subsets are explicitly included in the Zkt spec.

**Comment by nibrunieAtSi5** [comment]
The spec mentions

> All cryptography-specific instructions defined in this Vector Crypto specification (i.e., those in [zvkned], Zvknh[ab], [Zvkg], [Zvksed] and [zvksh] but not [zvbb],[zvkb], or [zvbc]) shall be executed with data-independent execution latency as defined in the RISC-V Scalar Cryptography Extensions specification.

This may need to be repeated in `Zvkt`

**Comment by nibrunieAtSi5** [comment]
Reference https://github.com/riscv/riscv-crypto/blob/master/doc/vector/riscv-crypto-spec-vector.adoc#1-extensions-overview

**Comment by aamartin0000** [comment]
Ok, thanks.  I just looked specifically at the Zvkt adoc, so I missed that.

**Comment by nibrunieAtSi5** [comment]
> Ok, thanks. I just looked specifically at the Zvkt adoc, so I missed that.

No worries.
