### ISSUE TITLE
Question about vaeskf2 pseudo code

### ISSUE THREAD

**Issue by Mingku-Chang** [riscv/riscv-crypto#358]
Hi,
I am studying Vector Crypto Specification 1.0.0-rc1.
I am confused about the pseudo-code of vaeskf2.
The variable "CurentRoundKey" appears to have 4 elements with a width of 8 bits.
The input data of the function "aes_subword_fwd" is 32-bit width.
So, how can I treat the statement "aes_subword_fwd(CurrentRoundKey[3])"?

**Comment by nibrunieAtSi5** [comment]
`CurrentRoundKey` is a 4-element array (`[3:0]`), each being 32-bit wide.
It appears the pseudo-code notation is not consistent with other pseudo code in the spec (e.g. `vsha2c` uses
```
  let MessageShedPlusC[3:0] : bits(4*SEW) = get_velem(vs1, 4*SEW, i);
```
where `<array>[3:0] : bits(4*SEW)` is used to split `4*SEW` bits into a 4-element array, each element being SEW bits wide.

To be consistent `bits(32)` should be replaced by `bits(128)` (Element Group Size for the round key)

**Comment by kdockser** [comment]
Fixed in vaeskf1 and vaeskf2.

**Comment by Mingku-Chang** [comment]
Hi @nibrunieAtSi5 & @kdockser,
Thanks for your help.
I guess the "foreach" statement in vsesfk1 is unnecessary.

**Comment by nibrunieAtSi5** [comment]
@Mingku-Chang , the `foreach` statement in https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vaeskf1.adoc is still required as it iterates over the various active element groups (not the word in a group). For example if `vl=12` (assuming for example VLEN=256, LMUL=2, SEW=32-bit), then `vaeskf1.vi` is still going to perform 3 parallel key schedule expansion and produce 3x128-bit.
