### ISSUE TITLE
Question about vghsh & vgmul pseudo code

### ISSUE THREAD

**Issue by Mingku-Chang** [riscv/riscv-crypto#361]
Hi,
There is the same pseudocode section on ghsh and ghmul, as shown below.
![image](https://github.com/riscv/riscv-crypto/assets/81346435/ec5a8a47-57d1-4bff-af53-3defcb4daf57)
I am confused by the statement "Z ^= H."
The data width of Z and H is 128 bits.
This section means when S[bit] is raised, do an Exclusive-OR on H and Z and then assign it to Z.
It looks like a 128-bit XOR operation.
On the other hand, It seems to do 32-bit Exclusive-OR on riscv-isa-sim.
Could you clarify this pseudocode?

**Comment by nibrunieAtSi5** [comment]
@Mingku-Chang thank you for asking this question, it looks like you find an answer.

For posterity:

https://github.com/riscv/riscv-crypto/blob/master/doc/vector/insns/vghsh.adoc

`riscv-isa-sim` bundle the 128-bit values `Z` and `H` as 4-element element group with 32-bit elements

https://github.com/riscv-software-src/riscv-isa-sim/blob/master/riscv/insns/vghsh_vv.h#L26
```
      if (EGU32x4_ISSET(S, bit)) {
        EGU32x4_XOREQ(Z, H);
      }
```

https://github.com/riscv-software-src/riscv-isa-sim/blob/d1680b75debfdb09905d08cdf0cd8104449ddb21/riscv/zvk_ext_macros.h#L944
```
// Performs  "MUT_A ^= CONST_B;", i.e., xor of the bytes
// in A (mutated) with the bytes in B (unchanged).
#define EGU32x4_XOREQ(MUT_A, CONST_B) \
  for (std::size_t idx = 0; idx < 4; ++idx) { \
    (MUT_A)[idx] ^= (CONST_B)[idx]; \
  }

```

@egouriou-rivos can maybe comment on why the values are split in 32-bit word in `riscv-isa-sim` (maybe for ease of manipulation / portability or to match the element group parameters used by `Zvkg` instructions)
