### ISSUE TITLE
Question about zvknha and zvknhb extension.

### ISSUE THREAD

**Issue by JerryShih** [riscv/riscv-crypto#364]
If one platform support SHA-512(zvknhb), will it also imply having zvknha?
The zvknhb could support both SHA-512 and SHA-256. Will the qemu or linux kernel need to enable SHA256 with zvknha extension or just use single zvknhb extension setting?

e.g.
```
# Will the following command have sha256?
qemu-riscv64 -cpu rv64,g=true,f=true,d=true,v=true,vlen=128,elen=64,vext_spec=v1.0,x-zvknhb=true
# Should we have the explicit sha256 setting?
qemu-riscv64 -cpu rv64,g=true,f=true,d=true,v=true,vlen=128,elen=64,vext_spec=v1.0,x-zvknha=true,x-zvknhb=true
```

**Comment by nibrunieAtSi5** [comment]
> Do we have sha256 with single "ZVKNHB" extension?
Yes


>  Should we have both "ZVKNHA" and "ZVKNHB" cpu setting in qemu if we try to have both sha256 and sha512?
No, those extensions are exclusive and cannot be enabled at the same time

**Comment by nibrunieAtSi5** [comment]
From https://github.com/riscv/riscv-crypto/blob/main/doc/vector/riscv-crypto-vector-zvknh.adoc

> Zvknhb supports SHA-256 and SHA-512.

**Comment by JerryShih** [comment]
Got it, thanks.

**Comment by nibrunieAtSi5** [comment]
⚠️ the answer to this question may actually change if https://github.com/riscv/riscv-isa-manual/pull/2635 make it through the review process.
