### ISSUE TITLE
Typo in v1.0.0

### ISSUE THREAD

**Issue by tobywenman** [riscv/riscv-crypto#367]
The title for appendix B is `Appendix B: Vector Bitmanip and Caryless Multiply Instructions.`,
 when presumably it should be `Appendix B: Vector Bitmanip and Carryless Multiply Instructions.`

**Comment by nibrunieAtSi5** [comment]
Hi @tobywenman, thank you for spotting this.

I open a PR to fix it https://github.com/riscv/riscv-crypto/pull/368/
