### ISSUE TITLE
Crypto subsets:  AES128 + AES256 always  come together ?

### ISSUE THREAD

**Issue by AndyGlew** [riscv/riscv-crypto#37]
PROPOSAL  -  POR

 AES 128 and AES 256 come together, they cannot be separated.

 If an implementation implements AES 128 it must implement AES 256, and vice versa.

(Placing my understanding  of consensus in meetings here in the issue statement.  Should be corrected if I have misunderstood.)

**Comment by AndyGlew** [comment]
Related issues:

#38 <-- combination of #36 and #37

**Comment by ben-marshall** [comment]
As decided at meeting 23/oct/2020 - closing all feature-group related issues and tracking in Jira.
