### ISSUE TITLE
Typo in the "Instruction Constraints" section

### ISSUE THREAD

**Issue by Mingku-Chang** [riscv/riscv-crypto#379]
In the section "Instruction Constraints," I guess the abbreviation "vgh*" might not be accurate.
I thought it represented 2 instructions: vghsh and vgmul.

**Comment by nibrunieAtSi5** [comment]
Thank you for spotting this @Mingku-Chang. I think the instructions were renamed at some point during the specification process and the instruction constraints section was not updated.

I have open https://github.com/riscv/riscv-crypto/pull/382 to fix the issue.

**Comment by nibrunieAtSi5** [comment]
PR fixing this has been merged in. I think this issue can be considered as resolved.

**Comment by wmat** [comment]
Closing as fix has was merged and is present in the Unpriv manual post integration.
