### ISSUE TITLE
Use of "dots" in assembly instruction names

### ISSUE THREAD

**Issue by grnewell** [riscv/riscv-crypto#42]
Issue to track how dots are used in the proposed instruction assembly names.

**Comment by grnewell** [comment]
I would remove the “.” unless the two (or more) instructions are really very close variations of one operation.  The .vv, .vi, .vs, .vx variations of essentially the same vector instruction are an example of this.  If the instructions represent different basic operations, then I would refrain from using the base + dot + suffix format to name them.  

Therefore, I would propose removing the dots from all the current mnemonics such as  saes32.encs, saes32.encsm where the underlying computation is different.  (Note, I also recommend removing the leading "s")

**Comment by ben-marshall** [comment]
> Therefore, I would propose removing the dots from all the current mnemonics such as saes32.encs, saes32.encsm where the underlying computation is different. (Note, I also recommend removing the leading "s")

Agreed with both points. I'll take this action once we know exactly what each instruction *should* be called.
