### ISSUE TITLE
Merge error in the file `https://github.com/riscv/riscv-crypto/blob/master/tools/patch-binutils.patch`

### ISSUE THREAD

**Issue by Lucas-Wye** [riscv/riscv-crypto#80]
Errors in the file [patch-binutils.patch](https://github.com/riscv/riscv-crypto/blob/master/tools/patch-binutils.patch)

**Comment by ben-marshall** [comment]
Hi @Lucas-Wye 
What errors are you seeing? Can you paste the output of "git apply" when applying the patch?
Thanks,
Ben

**Comment by ben-marshall** [comment]
What is the output of running `git log -n 5` inside `riscv-crypto/extern/riscv-gnu-toolchain/riscv-binutils`?
I'm trying to work out if the `start-from-scratch` script is checking out the right base commit for binutils. It *should* be `3e5f50f31348d05144966545d862a3172d315230`, but I see now it's actually checking out a branch pointer, which might have changed recently.

**Comment by Lucas-Wye** [comment]
![图片](https://user-images.githubusercontent.com/30680577/110459178-9fc25780-8107-11eb-84e2-a1d37aa06be6.png)
Yes, the commit id is wrong.

**Comment by ben-marshall** [comment]
Ah, that explains it then. I've just run a clean checkout and start-from-scratch and it is working for me. Let me know if changing the commit makes it work for you?

**Comment by Lucas-Wye** [comment]
Thank you! It works for me now.

**Comment by ben-marshall** [comment]
Glad to hear it! :-)
