### ISSUE TITLE
Section 3.5: aes64dsm or aes64ds?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-crypto#94]
Section 3.5 has a mixture of references to aes64dsm and aes64ds. I think it should be aes64ds?

**Comment by ben-marshall** [comment]
Hi James
Ugh. yes, you are absolutely right. This was also present in the v0.9.1 release, so made it past quite a lot of people. I've fixed it in commit [f8fd753](https://github.com/riscv/riscv-crypto/commit/f8fd75c93a9911bf42bf34915b5d6afafa21b43f), and it will appear in the next release. I'll leave this issue open until that happens so we don't get duplicates raised.
Thanks a lot,
Ben
