### ISSUE TITLE
Section 3.10: are bits 31:30 0?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-crypto#95]
Are bits 31:30 in the decode of aes64ks1i zero?

Hi @ben-marshall - should I open separate issues for these documentation things, or accumulate in one issue?

**Comment by ben-marshall** [comment]
Hi @JamesKenneyImperas 

@ksyx  spotted this in #96 too. I'll repeat what I said there:

> [...] this is a tool bug related to Wavedrom which is used to generate the encoding diagrams. Hence, this and all other such problems will be fixed when I update my local version of wavedrom and which fixes this bug.

So yes, bits 31:30 _are_ zero. But I forgot to update my tooling before doing the release, and missed this before creating it. I'll leave this issue open until the _next_ release, so people see what's up. Sorry about this!

About separate v.s. combined issues: separate issues would be my preference, I struggle to track multiple things in a single thread.

Cheers,
Ben
