### ISSUE TITLE
packu[h] -> packu[w]?

### ISSUE THREAD

**Issue by JamesKenneyImperas** [riscv/riscv-crypto#98]
The change notes for 0.9.2 refer twice to `packu[h]` instructions. I don't think there is any such instruction `packuh` - do you mean `packuw`?

Thanks.

**Comment by JamesKenneyImperas** [comment]
(Also, can you clarify the status of packu* and rev8.w? The change log says they are removed, but they are still in the specification.)

**Comment by ben-marshall** [comment]
> The change notes for 0.9.2 refer twice to packu[h] instructions. I don't think there is any such instruction packuh - do you mean packuw?

Yes, that should have been `packuw`

> (Also, can you clarify the status of packu* and rev8.w? The change log says they are removed, but they are still in the specification.)

Gah. This release needs a complete do over, I'm sorry about this.

So, yes, these instructions _should have been removed_. Clearly I missed some (all?!) references to them in the spec.

I'll fix this up asap.

Cheers,
Ben

**Comment by ben-marshall** [comment]
@JamesKenneyImperas  - Where in the spec are you seeing `rev8.w` and `packu*`? I can only see them in the appendix and in the `Zkt` section, and am now double checking I've not done something even more stupid than I thought?

**Comment by ben-marshall** [comment]
Hopefully the commit above removes all unncessary mention of `packu[w]` and `rev8.w`. They _should_ still be mentioned in the `Zkt` section. I hope this is more clear? If not let me know.
Cheers,
Ben

**Comment by JamesKenneyImperas** [comment]
Hi Ben - Ok, I saw them in the Zkt section (5.4.5) and misunderstood what that was all about - sorry.
